### ISSUE TITLE
Delimiter for creating multiple fake items not available on en-US keyboard

### ISSUE THREAD

**Issue by e28eta** [deanishe/alfred-fakeum#1]
I wasn't able to figure out how to type the ⟩ (U+27E9) character from my keyboard.

It'd be nice if the delimiter was configurable, to make it usable

**Comment by deanishe** [comment]
You're not meant to enter the delimiter by hand. It's just there to help the workflow parse your query.

If you want multiple datasets, hit TAB on one of the datatypes. It will autocomplete the name and add the delimiter and a trailing space.

Delete the trailing space to go back to the list of datatypes.
