### ISSUE TITLE
FAKERS keys are case sensitive when generating multiple items

### ISSUE THREAD

**Issue by e28eta** [deanishe/alfred-fakeum#3]
"fake name" works.
"fake Name ⟩ 5" works.

"fake name ⟩ 5" produces "Error in workflow ... u'name'"

PS: Thanks for all the hard work you've done for Alfred workflows. Today's the first day I've looked into them, and I'm amazed by the work you've done. http://www.deanishe.net/alfred-workflow/ is most excellent!

**Comment by deanishe** [comment]
See my other responses. The solution is to use the TAB key to autocomplete the correct name of a fake datatype if you want multiple sets of data.
