### ISSUE TITLE
Request: Ability to generate entire User json object

### ISSUE THREAD

**Issue by AYapejian** [deanishe/alfred-fakeum#4]
Would be sweet to be able to get a json object or array of json objects that describes an entire "User" something like below with all the fields this workflow supports. 

```
{
   firstName: 'RandomFirstName',
   lastName:  'randomLastName'
}
```

**Comment by deanishe** [comment]
The workflow doesn't generate any data itself. You'd need to add a new generator to the faker library included:

http://faker.readthedocs.io/en/master/index.html

This also seems like a very specific case without obvious broad appeal, so I'm not sure it belongs in the workflow. 

Perhaps a plugin system to allow users to add their own generators would be a good idea.
