### ISSUE TITLE
other locale then English doesn't work

### ISSUE THREAD

**Issue by josefglatz** [deanishe/alfred-fakeum#6]
I'm running High Sierra, downloaded the workflow from GitHub Release page and if I only set locale to German the "fake" keyword does not suggest "Name" or the other arguments.

Do I have to download faker data from somewhere?

**Comment by deanishe** [comment]
It was a silly bug. The other locales worked, but the whole thing fell apart if English (or another complete locale) wasn't selected.

Should be fixed in [v2.1](https://github.com/deanishe/alfred-fakeum/releases/tag/v2.1).
